sudo: required

language:
  - cpp

services:
  - docker

script:
  - ./build-docker-image.sh
  - ./build-debug.sh
  - ./build-release.sh
  - build-debug/tests/bpftrace_test --gtest_filter=-codegen*
  - build-release/tests/bpftrace_test --gtest_filter=-codegen*
